import coffeePng from '../../../../assets/images/coffee.png';

export const mockMenu = [
  { title: '人气Top', id: 0 },
  { title: '生酪拿铁', id: 1 },
  { title: '丝绒拿铁', id: 2 },
  // { title: '生椰家族', id: 4 },
  // { title: '小黑杯', id: 5 },
  // { title: '瑞纳冰', id: 6 },
  // { title: '经典拿铁', id: 7 },
  // { title: '大师咖啡', id: 8 },
  // { title: '不喝咖啡', id: 9 },
  // { title: '甜品小点', id: 10 },
];

export const mockList = [
  // 人气Top
  [
    {
      type: 'card',
      title: '人气Top',
      subTitle: '必喝爆款，瑞幸精品',
    },
    {
      id: 1,
      title: '人气Top',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 2,
      title: '人气Top',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 3,
      title: '人气Top',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 4,
      title: '人气Top',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 5,
      title: '人气Top',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
  ],
  // 生酪拿铁
  [
    {
      type: 'card',
      title: '生酪拿铁',
      subTitle: '必喝爆款，瑞幸精品',
    },
    {
      id: 6,
      title: '生酪拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 7,
      title: '生酪拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 8,
      title: '生酪拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 9,
      title: '生酪拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 10,
      title: '生酪拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 11,
      title: '生酪拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 12,
      title: '生酪拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
  ],
  // 丝绒拿铁
  [
    {
      type: 'card',
      title: '丝绒拿铁',
      subTitle: '必喝爆款，瑞幸精品',
    },
    {
      id: 13,
      title: '丝绒拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 14,
      title: '丝绒拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 15,
      title: '丝绒拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
    {
      id: 16,
      title: '丝绒拿铁',
      desc: '2022拿铁冠军',
      originalPrice: 32,
      discountPrice: 28,
      handPrice: 15,
      imageUrl: coffeePng,
    },
  ],
];
